/*
    Dusk Source Code
    Copyright (C) 2019 Prevost Baptiste
*/
#pragma once

#if DUSK_D3D12
#include <d3d12.h>

static constexpr D3D12_TEXTURE_ADDRESS_MODE TEXTURE_ADDRESS_LUT[eSamplerAddress::SAMPLER_ADDRESS_COUNT] = {
    D3D12_TEXTURE_ADDRESS_MODE_WRAP,
    D3D12_TEXTURE_ADDRESS_MODE_MIRROR,
    D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
    D3D12_TEXTURE_ADDRESS_MODE_BORDER,
    D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE
};

static constexpr D3D12_FILTER FILTER_LUT[eSamplerFilter::SAMPLER_FILTER_COUNT] = {
    D3D12_FILTER_MIN_MAG_MIP_POINT,
    D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT,
    D3D12_FILTER_MIN_MAG_MIP_LINEAR,
    D3D12_FILTER_ANISOTROPIC,
    D3D12_FILTER_ANISOTROPIC,

    D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
    D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT,
    D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
    D3D12_FILTER_COMPARISON_ANISOTROPIC,
    D3D12_FILTER_COMPARISON_ANISOTROPIC,
};

struct Sampler
{
    D3D12_CPU_DESCRIPTOR_HANDLE descriptor;
};
#endif
