/*
    Dusk Source Code
    Copyright (C) 2019 Prevost Baptiste
*/
#pragma once

#if DUSK_D3D12
#include <Rendering/RenderDevice.h>
#include <d3d12.h>

static constexpr D3D12_COMPARISON_FUNC COMPARISON_FUNCTION_LUT[eComparisonFunction::COMPARISON_FUNCTION_COUNT] = {
    D3D12_COMPARISON_FUNC_NEVER,
    D3D12_COMPARISON_FUNC_ALWAYS,
    D3D12_COMPARISON_FUNC_LESS,
    D3D12_COMPARISON_FUNC_GREATER,
    D3D12_COMPARISON_FUNC_LESS_EQUAL,
    D3D12_COMPARISON_FUNC_GREATER_EQUAL,
    D3D12_COMPARISON_FUNC_NOT_EQUAL,
    D3D12_COMPARISON_FUNC_EQUAL
};
#endif
