/*
    Dusk Source Code
    Copyright (C) 2019 Prevost Baptiste
*/
#pragma once

#if DUSK_D3D11
#include <Rendering/RenderDevice.h>
#include <d3d11.h>

static constexpr D3D11_COMPARISON_FUNC D3D11_COMPARISON_FUNCTION[eComparisonFunction::COMPARISON_FUNCTION_COUNT] =
{
    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_NEVER,
    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_ALWAYS,

    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS,
    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_GREATER,

    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS_EQUAL,
    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_GREATER_EQUAL,

    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_NOT_EQUAL,
    D3D11_COMPARISON_FUNC::D3D11_COMPARISON_EQUAL,
};
#endif
